site_name: HotelScape
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
    - Installation: installation.md
    - Project Layout: project_layout.md
theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
    accent: deep purple
plugins:
  - search
