"""empty message

Revision ID: 043e8fba837a
Revises: de0d79366901
Create Date: 2022-08-04 23:33:33.210116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "043e8fba837a"
down_revision = "de0d79366901"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_table(
        "room_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "number_of_beds",
            sa.Enum(
                "single_bed",
                "double_beds",
                "twin_beds",
                "king_size_bed",
                name="numberofbeds",
            ),
            nullable=True,
        ),
        sa.Column("satelite_tv", sa.Boolean(), nullable=True),
        sa.Column("minibar", sa.Boolean(), nullable=True),
        sa.Column("conditioner_or_fan", sa.Boolean(), nullable=True),
        sa.Column("in_room_safe", sa.Boolean(), nullable=True),
        sa.Column("tea_coffee_making", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_room_types_id"), "room_types", ["id"], unique=True
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guest_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("ts_created", sa.DateTime(), nullable=True),
        sa.Column("ts_updated", sa.DateTime(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reservations_id"), "reservations", ["id"], unique=False
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("room_type_id", sa.Integer(), nullable=True),
        sa.Column("current_price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_id"), "rooms", ["id"], unique=True)
    op.create_table(
        "reserved_rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=True),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reserved_rooms")
    op.drop_index(op.f("ix_rooms_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_reservations_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_room_types_id"), table_name="room_types")
    op.drop_table("room_types")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
