"""empty message

Revision ID: 187a4af528b3
Revises: 043e8fba837a
Create Date: 2022-08-04 23:36:05.695366

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "187a4af528b3"
down_revision = "043e8fba837a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
