"""empty message

Revision ID: 32535fbbb7ae
Revises: 6d208a66d4e6
Create Date: 2022-07-31 22:38:25.337018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32535fbbb7ae'
down_revision = '6d208a66d4e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('conditioner_or_fan', sa.Boolean(), nullable=True))
    op.drop_column('room_types', 'air_conditiong_or_fan_cooling')
    op.alter_column('rooms', 'room_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'room_type_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'room_type_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'room_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('room_types', sa.Column('air_conditiong_or_fan_cooling', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('room_types', 'conditioner_or_fan')
    # ### end Alembic commands ###
