"""empty message

Revision ID: af573c50e9f9
Revises: f2b79e53eed0
Create Date: 2022-08-07 12:43:01.425719

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'af573c50e9f9'
down_revision = 'f2b79e53eed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
