"""empty message

Revision ID: b1aedcdc4406
Revises: af573c50e9f9
Create Date: 2022-08-07 19:09:12.992280

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b1aedcdc4406'
down_revision = 'af573c50e9f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'])
    op.alter_column('clients', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('clients_email_key', 'clients', type_='unique')
    op.drop_constraint('clients_phone_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_phone_key', 'clients', ['phone'])
    op.create_unique_constraint('clients_email_key', 'clients', ['email'])
    op.alter_column('clients', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'room_id')
    # ### end Alembic commands ###
