"""empty message

Revision ID: de0d79366901
Revises: 
Create Date: 2022-08-04 23:28:56.617976

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de0d79366901"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
