name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Set up cache
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Run env
        run: pip install passlib
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pasword
          POSTGRES_SERVER: locahost
          POSTGRES_DATABASE: db
          POSTGRES_TEST_DATABASE: test-dv
          ALGORITHM: HS256
          JWT_SECRET_KEY: JWT_SECRET_KEY
          JWT_REFRESH_SECRET_KEY: JWT_REFRESH_KEY
      - name: Run tests
        run: poetry run pytest --cov . -n
